## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [1]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [2]:
# your code here
input_size = 2
output_size = 2

model1 = nn.Sequential(OrderedDict([
   ('hidden', nn.Linear(input_size, 3)),
    ('activation1', nn.Sigmoid()),
    ('output', nn.Linear(3, output_size)),
    ('activation2', nn.Sigmoid())
]))

model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(input_size, 4)),
    ('activation1', nn.Sigmoid()),
    ('output', nn.Linear(4, output_size)),
    ('activation2', nn.Sigmoid())
]))

model3 = nn.Sequential(OrderedDict([
    ('hidden1', nn.Linear(input_size, 2)),
    ('activation1', nn.Sigmoid()),
    ('hidden1', nn.Linear(2, 4)),
    ('activation2', nn.Sigmoid()),
    ('output', nn.Linear(4, output_size)),
    ('activation3', nn.Sigmoid())
]))

In [3]:
print(model1)
print(model2)
print(model3)

Sequential(
  (hidden): Linear(in_features=2, out_features=3, bias=True)
  (activation1): Sigmoid()
  (output): Linear(in_features=3, out_features=2, bias=True)
  (activation2): Sigmoid()
)
Sequential(
  (hidden): Linear(in_features=2, out_features=4, bias=True)
  (activation1): Sigmoid()
  (output): Linear(in_features=4, out_features=2, bias=True)
  (activation2): Sigmoid()
)
Sequential(
  (hidden1): Linear(in_features=2, out_features=4, bias=True)
  (activation1): Sigmoid()
  (activation2): Sigmoid()
  (output): Linear(in_features=4, out_features=2, bias=True)
  (activation3): Sigmoid()
)


In [4]:
# your code here
data_in = torch.tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])


In [5]:
# your code here
data_target = torch.tensor([[0., 0.], [0., 1.], [0., 1.], [1., 0.]])
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [6]:
# your code here
# Train the model
bestEpoch = []

def train(trainNumber, model):
    num_epochs = 10000
    found = False
    
    criterion = nn.MSELoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=0.1)
    
    print(f"\nModel {trainNumber}:")
    
    for epoch in range(num_epochs):
        # Forward pass
        outputs = model(data_in)
        loss = criterion(outputs, data_target)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        predicted = torch.round(outputs)
        accuracy = (predicted == data_target).float().mean()
        
        # Print the loss every 1000 epochs
        if (epoch + 1) % 1000 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}, Accuracy: {accuracy}')

        if accuracy == 1.0 and found == False:
            #print(f"Model {trainNumber} reached 100% accuracy at epoch {epoch+1}")
            bestEpoch.append([f"Model {trainNumber} reached accuracy 100% accuracy at epoch {epoch + 1}", trainNumber, epoch + 1, model])
            found = True
    
    if found == False:
        bestEpoch.append([f"Model {trainNumber} hasn't reached accuracy 100% in {num_epochs} epochs", trainNumber, num_epochs, model])

In [7]:
# your code here
# visualize the resuts

train(1, model1)
train(2, model2)
train(3, model3)

print('\n')
for best in bestEpoch:
    print(best[0])


Model 1:
Epoch [1000/10000], Loss: 0.2157, Accuracy: 0.625
Epoch [2000/10000], Loss: 0.2105, Accuracy: 0.625
Epoch [3000/10000], Loss: 0.2006, Accuracy: 0.625
Epoch [4000/10000], Loss: 0.1858, Accuracy: 0.625
Epoch [5000/10000], Loss: 0.1700, Accuracy: 0.75
Epoch [6000/10000], Loss: 0.1565, Accuracy: 0.875
Epoch [7000/10000], Loss: 0.1468, Accuracy: 0.875
Epoch [8000/10000], Loss: 0.1403, Accuracy: 0.875
Epoch [9000/10000], Loss: 0.1360, Accuracy: 0.875
Epoch [10000/10000], Loss: 0.1328, Accuracy: 0.875

Model 2:
Epoch [1000/10000], Loss: 0.2101, Accuracy: 0.625
Epoch [2000/10000], Loss: 0.1952, Accuracy: 0.625
Epoch [3000/10000], Loss: 0.1730, Accuracy: 0.75
Epoch [4000/10000], Loss: 0.1537, Accuracy: 0.75
Epoch [5000/10000], Loss: 0.1411, Accuracy: 0.875
Epoch [6000/10000], Loss: 0.1315, Accuracy: 0.875
Epoch [7000/10000], Loss: 0.1186, Accuracy: 0.875
Epoch [8000/10000], Loss: 0.0980, Accuracy: 1.0
Epoch [9000/10000], Loss: 0.0724, Accuracy: 1.0
Epoch [10000/10000], Loss: 0.0492, A

In [9]:
# your code here
# print model wights

bestModel = min(bestEpoch, key=lambda x: x[2])
print(f"Best model is model {bestModel[1]}\n")

print("Model weights:")
for x in bestModel[3].children():
    if(type(x) == torch.nn.modules.linear.Linear):
        print(x.weight)

Best model is model 2

Model weights:
Parameter containing:
tensor([[ 0.9575,  2.0631],
        [-1.9464, -0.8776],
        [-3.4518, -3.4067],
        [-2.6753, -2.6139]], requires_grad=True)
Parameter containing:
tensor([[ 3.2934, -2.9974, -2.9475, -4.0839],
        [-0.4214,  0.1016, -3.8873,  2.9128]], requires_grad=True)
